### ISSUE TITLE
Error when starting from command line

### ISSUE THREAD

**Issue by ghost** [loomchild/segment#18]
There is an error starting either the jar or the script in the zip from the command line.
Kubuntu 20.10, OpenJDK

ruud@DESKTOP:/media/ruud/data3/corpora$ ./segment-2.0.1/bin/segment -s segment.srx -l nl -i klantencorpus_txt.txt -o out.txt
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at net.loomchild.segment.ui.console.Segment.createFileReader(Segment.java:250)
        at net.loomchild.segment.ui.console.Segment.createTextReader(Segment.java:230)
        at net.loomchild.segment.ui.console.Segment.segment(Segment.java:183)
        at net.loomchild.segment.ui.console.Segment.run(Segment.java:115)
        at net.loomchild.segment.ui.console.Segment.main(Segment.java:88)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more

**Comment by janissl** [comment]
The source has not been adapted for a Java version greater than 8 or OpenJDK. If you want to run it on a newer Java version, add the two dependencies below in pom.xml of segment module.

```
<!-- https://mvnrepository.com/artifact/javax.xml.bind/jaxb-api -->
<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.3.1</version>
</dependency>

<!-- https://mvnrepository.com/artifact/org.glassfish.jaxb/jaxb-runtime -->
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-runtime</artifactId>
    <version>2.3.2</version>
</dependency>
```
 jaxb-runtime has newer versions in Maven repo (the latest version is 3.0.0) but I haven't tried to use them yet.

**Comment by ghost** [comment]
This requires me to be a programmer, which I am not. Maybe a programmer around here can do the update? Even when adding this to the pom, it fails.

**Comment by loomchild** [comment]
Thanks for raising this issue @baarsrj, and thanks @janissl for suggesting a solution. I will try to fix and release segment today,

**Comment by loomchild** [comment]
Ah, in fact, I already resolved this problem and the code compiles and runs under Java 11, just didn't release the latest version due to some issues with my environment.

**Comment by loomchild** [comment]
New release is available, please let me know if it works: https://github.com/loomchild/segment/releases/tag/2.0.2

(I haven't uploaded the library to Maven Central yet though, haven't done it for a long time and it seems it requires more work)

**Comment by loomchild** [comment]
I also managed to deploy it to Maven Central and fix unit tests, the latest release is https://github.com/loomchild/segment/releases/tag/2.0.3. Please close this ticket if it works as expected.

**Comment by loomchild** [comment]
I am closing this issue, feel free to reopen if it still doesn't work with the latest version.
